zuul:
  routes:
    product: /myProduct/**
  sensitive-headers:
#  ignored-patterns:
#    - /**/product/listForOrder
#    myProduct:
#      path: /myProduct/**
#     serviceId: product
management:
  security:
    enabled: false    
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: 123456
