spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qinjiaxin1/config_test.git
          username: 732753413@qq.com
          password: slk32068
          basedir: G://config/basedir
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: 123456
env:
 dev2
ted:
 Love you forever,Ted ^^
